---
- name: install zsh
  apt: pkg=zsh state=present

- name: install prezto
  git: repo=https://github.com/sorin-ionescu/prezto.git dest=~/.zprezto
  sudo: false

- name: add prezto conf files
  script: create_conf.sh creates=~/.zshrc

- name: switch to ZSH
  user: name={{ansible_ssh_user}} shell=/bin/zsh
  sudo: True
